api_token_env: CROWDIN_API_TOKEN
project_id_env: CROWDIN_PROJECT_ID
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

language_mapping:
  chinese-simplified: zh-CN
  english: en
  french: fr
  german: de
  hindi: hi
  indonesian: id
  italian: it
  japanese: ja
  korean: ko
  malay: ms
  portuguese: pt
  spanish: es
  thai: th
  urdu: ur
  vietnamese: vi

files:
  - source: "src/i18n/translations/en.json"
    translation: "src/i18n/translations/%locale%.json"
